### ISSUE TITLE
src/index.scss文件的引入var.scss错误

### ISSUE THREAD

**Issue by xushijie10086** [Clementine1995/react-ts-template#3]
./react-ts-template/src/index.scss文件引入的var.scss文件路径错误
      不知道是作者故意的还是怎么。。。

> 原文件
```css

@import './styles/reset.css';
@import 'var.scss';

.app{  
  // background: $red;
  .aps {
    width: 50px;
    @include ellipsis;
  }
}

```

> 修改为

```css
@import './styles/reset.css';
@import './styles/var.scss';

.app{  
  // background: $red;
  .aps {
    width: 50px;
    @include ellipsis;
  }
}
```
